### ISSUE TITLE
Using 5'/3' variants does not work

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#1028]
**Describe the bug**
Filter a case, e.g., hom. recessive. Enable 5'/3' variants.

**To Reproduce**
1. Setup filter with hom. recessive.
2. Use "More..." => Effects / Enable 5'/3' exonic.
3. Click Filter Variants button.
4. Nothing happens

**Expected behavior**
Variants should be properly filtered.

**Screenshots**
![image](https://github.com/bihealth/varfish-server/assets/521780/81eaf13c-e020-449a-8c81-fc2eb2f0b48c)
![image](https://github.com/bihealth/varfish-server/assets/521780/e8b93c50-7579-48ae-8a2f-dae74ca3bcfe)

**Comment by stolpeo** [comment]
Closed with #1041
