### ISSUE TITLE
[vuejs] [smallvariant] Setting query impact to whole transcript does not work

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#1043]
**Describe the bug**
Setting the filter impact to `whole_transcript` disables the filter button. Also selecting any of `UTR exonic/intronic` in Variants & Effects disables the filter button.

**Screenshots**
![image](https://github.com/bihealth/varfish-server/assets/3340720/9d5f3058-a7d8-461c-aa2c-e4498b6c9146)

**Comment by stolpeo** [comment]
Could you please double-check if this is still the case? We've unrolled a patch that touched this part of the interface. Right now I can't reproduce it.

**Comment by xiamaz** [comment]
No just didnt find manuels before you fixed it. Thanks!
