### ISSUE TITLE
[small variants] Certain variants return infinity in scores

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#1117]
For some variants, e.g. the following:

`1:48,877,261C>T`

`-infinity` is returned for certain scores. This values still returns a benign classification, but should be detected to be an invalid value:

![image](https://github.com/bihealth/varfish-server/assets/3340720/18de2ad3-5019-450c-bf07-e313e49ddb22)

**Comment by xiamaz** [comment]
This seems to occur if dbnsfp or similar returns an empty score value instead of nothing

**Comment by holtgrewe** [comment]
Also, REVEL seems to be missing in many cases? I'll have a look.
