### ISSUE TITLE
Remove necessity nltk data download

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#1259]
**Describe the bug**
We currently use nltk in a couple of places for its stemming functionality. This causes build failures if the nltk data cannot be downloaded for the Docker build.

**To Reproduce**
1. Look here https://github.com/bihealth/varfish-server/actions/runs/7243494405/job/19730394027?pr=1247

```
Dockerfile:96
--------------------
  95 |     # Install Python dependencies via pipenv.
  96 | >>> RUN PIPENV_VENV_IN_PROJECT=1 pipenv install \
  97 | >>>         --python=/usr/local/bin/python \
  98 | >>>         --categories=packages,prod-packages,ldap-packages \
  99 | >>>         --deploy && \
 100 | >>>     pipenv run python -m nltk.downloader stopwords
 101 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c PIPENV_VENV_IN_PROJECT=1 pipenv install         --python=/usr/local/bin/python         --categories=packages,prod-packages,ldap-packages         --deploy &&     pipenv run python -m nltk.downloader stopwords" did not complete successfully: exit code: 2
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c PIPENV_VENV_IN_PROJECT=1 pipenv install         --python=/usr/local/bin/python         --categories=packages,prod-packages,ldap-packages         --deploy &&     pipenv run python -m nltk.downloader stopwords" did not complete successfully: exit code: 2
```

**Expected behavior**
Docker build should succeed

**Additional context**
N/A

**Comment by stolpeo** [comment]
RCA
====

The `nltk` package has been used in the pre-vue interface in a template tag for creating the pubmed linkout. The list of stopwords have been moved to a txt file and the functionality was re-created in vue. We never get an updated list of stop words, but this is not required.

Solution
======
The `nltk` package can be safely removed.
