### ISSUE TITLE
varfish irresponsive after deleting a sample uploaded to category 

### ISSUE THREAD

**Issue by snesic** [bihealth/varfish-server#237]
**Describe the bug**
We tested if a sample could be uploaded to a category. It was successfully uploaded and, as expected, did not appear anywhere except on the Django admin site. After deleting the sample manually, varfish became irresponsive so we had to physically restart the server. There were no issues with the database whatsoever. 

**To Reproduce**
1. Create a category
2. Upload a sample 
3. Go to the Django admin site
4. Delete the sample  
5.  Check if the webpage is responsive

**Expected behavior**
Same as deleting a sample from a project, varfish would work normally. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.2
 - Browser: Mozilla Firefox 
 - Version: 94.0

**Varfish Server (please complete the following information):**
 - OS: openSUSE Leap
 - Version: 15.2
 - Varfish version: 0.27

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
### Root Cause Analysis

N/A

There is no need for a root cause analysis. Categories are handled differently from projects for display/templates in sodar-core and thus also VarFish.

We can just go ahead and prevent data upload via API to categories

**Comment by holtgrewe** [comment]
### Resolution Proposal

It is sufficient to prevent upload of cases to categories.

#### Resolution Proposal Summary

**Affected Components**
- VarFish Server (only)

**Affected Modules/Files**
- `importer` (only)

**Required Architectural Changes**
- none

**Resolution Sketch**
- Any API call should check whether the given project is a project and not a category.
- In the case of being a category, the view should send a HTTP 400 to the user.

**Further Context**
- Maybe we can put central logic for the "is not a category" check into a view/API view parent class/mixin in sodar-core directly.
