### ISSUE TITLE
"MT" button does not work any more

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#240]
**Describe the bug**
Clicking on the blue "MT" button next to any variant does not correctly open MutationTaster any more.

**To Reproduce**
1. Run any query with at least one variant in the result.
2. Click "MT" button.
3. You will see the following MutationTaster error from "Screenshots"

**Expected behavior**
MutationTaster result for the variant should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/521780/142861308-c2661c26-043c-4aea-a0f9-3ab3becbd581.png)

**Additional context**
N/A

**Comment by holtgrewe** [comment]
### Root Cause Analysis

We are using the following JavaScript code to enter MutationTaster:

```js
function mutationTaster(chromosome, position, ref, alt) {
    var form = $('<form target="_blank" method="POST" action="http://www.mutationtaster.org/cgi-bin/MutationTaster/MT_ChrPos.cgi">');
    form.append($('<input type="hidden" name="chromosome" value="' + chromosome + '">'));
    form.append($('<input type="hidden" name="position" value="' + position + '">'));
    form.append($('<input type="hidden" name="ref" value="' + ref + '">'));
    form.append($('<input type="hidden" name="alt" value="' + alt + '">'));
    form.appendTo('body').submit();
}
```

However, MutationTaster has changed its location apparently and there also is a more modern MutationTaster2021.

- https://www.mutationtaster.org/
- https://www.genecascade.org/MutationTaster2021/#transcript

**Comment by holtgrewe** [comment]
### Resolution Proposal

We can simply change the current location. Additionally, we should ask the MutationTaster authors what the best way would be for the future.

**Resolution Proposal Summary**

**Affected Components**
VarFish Server (only)

**Affected Modules/Files**
`filter_form.js`

**Required Architectural Changes**
none

**Resolution Sketch**
1. Adjust the post URL & test that this works.
2. Contact MT authors for advise

**Comment by holtgrewe** [comment]
@dseelow ping

**Comment by domibln** [comment]
Wobei
https://www.mutationtaster.org/MT85/ChrPos85.cgi
noch besser wäre, das ist die Version, die MutationDistiller verwendet.

Langfristig soll es irgendwann so werden, daß die MutationTaster- und die Genomversion als Parameter übergeben werden.
