### ISSUE TITLE
SODAR to IGV transfer error

### ISSUE THREAD

**Issue by sczakihl** [bihealth/varfish-server#261]
On trying to open an IGV session via SODAR, the following error message appears:

_Errors were encountered loading the session: https://sodar-davrods.bihealth.org/sodarZone/projects/17/17328747-5a36-43bc-900d-5941008c872a/sample_data/study_0dedaff9-0774-4513-b890-e7b43c6cf56b/assay_f44a2ee1-f660-4a2e-8928-760f9394188c/LB21_3176-N1-DNA1-WES1/ngs_mapping/2021-11-22/out/bwa.LB21_3176-N1-DNA1-WES1.bam   org.broad.igv.exceptions.DataLoadException: An error occurred while accessing: https://sodar-davrods.bihealth.org/sodarZone/projects/17/17328747-5a36-43bc-900d-5941008c872a/sample_data/study_0dedaff9-0774-4513-b890-e7b43c6cf56b/assay_f44a2ee1-f660-4a2e-8928-760f9394188c/LB21_3176-N1-DNA1-WES1/ngs_mapping/2021-11-22/out/bwa.LB21_3176-N1-DNA1-WES1.bam Error loading BAM file: htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available) https://sodar-davrods.bihealth.org/sodarZone/projects/17/17328747-5a36-43bc-900d-5941008c872a/sample_data/study_0dedaff9-0774-4513-b890-e7b43c6cf56b/assay_f44a2ee1-f660-4a2e-8928-760f9394188c/LB21_3175-N1-DNA1-WES1/ngs_mapping/2021-11-22/out/bwa.LB21_3175-N1-DNA1-WES1.bam   org.broad.igv.exceptions.DataLoadException: An error occurred while accessing: https://sodar-davrods.bihealth.org/sodarZone/projects/17/17328747-5a36-43bc-900d-5941008c872a/sample_data/study_0dedaff9-0774-4513-b890-e7b43c6cf56b/assay_f44a2ee1-f660-4a2e-8928-760f9394188c/LB21_3175-N1-DNA1-WES1/ngs_mapping/2021-11-22/out/bwa.LB21_3175-N1-DNA1-WES1.bam Error loading BAM file: htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available) https://sodar-davrods.bihealth.org/sodarZone/projects/17/17328747-5a36-43bc-900d-5941008c872a/sample_data/study_0dedaff9-0774-4513-b890-e7b43c6cf56b/assay_f44a2ee1-f660-4a2e-8928-760f9394188c/LB21_3175-N1-DNA1-WES1/variant_calling/2021-11-22/out/bwa.gatk_hc.LB21_3175-N1-DNA1-WES1.vcf.gz   org.broad.igv.exceptions.DataLoadException: Unable to create BasicFeatureReader using feature file , for input source: https://sodar-davrods.bihealth.org/sodarZone/projects/17/17328747-5a36-43bc-900d-5941008c872a/sample_data/study_0dedaff9-0774-4513-b890-e7b43c6cf56b/assay_f44a2ee1-f660-4a2e-8928-760f9394188c/LB21_3175-N1-DNA1-WES1/variant_calling/2021-11-22/out/bwa.gatk_hc.LB21_3175-N1-DNA1-WES1.vcf.gz_ 

The same happens, when trying to download the IGV session manually and opening it. When trying to download the bam-file from SODAR the following SODAR error message appears:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

**Comment by holtgrewe** [comment]
Please try again

**Comment by sczakihl** [comment]
Perfect, thanks! 👍
