### ISSUE TITLE
Replace wrongly migrated icons.

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#284]
Some icons have been replaced wrongly during the icon migration. Please add every occurrence (screenshot and/or description) here in the comments. After some time period, they will be fixed in bulk.

- **Project overview**
    - ![MicrosoftTeams-image](https://user-images.githubusercontent.com/1266531/151151503-875578c1-e05b-4c80-8a76-6c7964ba380f.png)
- **Joint Filtration**
    - ![image](https://user-images.githubusercontent.com/521780/153565508-c047d2f9-5b39-4ee4-af65-a084781b576e.png)

**Comment by holtgrewe** [comment]
Let's do this before the 1.2 release.

**Comment by holtgrewe** [comment]
The problem only occurs on initial load, after refresh it does not apepar.
