### ISSUE TITLE
VarFish site data archive corruption?

### ISSUE THREAD

**Issue by aciolfi** [bihealth/varfish-server#3]
Hi there,

We're trying to install VarFish according your instructions (https://varfish-server.readthedocs.io/en/latest/admin_install.html), but when we download and extract the VarFish site data archive we get always the same error:

```
$ tar xfv varfish-site-data-v0.22.2-20210212.tar.gz
volumes/
volumes/redis/
volumes/redis/data/
volumes/redis/data/dump.rdb
volumes/postgres/
volumes/postgres/data/
volumes/postgres/data/pg_subtrans/
volumes/postgres/data/pg_subtrans/0000
[...]
volumes/postgres/data/pg_wal/000000010000010E0000001E
volumes/postgres/data/pg_wal/000000010000010A0000008F
volumes/postgres/data/pg_wal/000000010000010B000000BD
volumes/postgres/data/pg_wal/000000010000010500000028
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

We've downloaded this file: https://file-public.bihealth.org/transient/varfish/varfish-site-data-v0.22.2-20210212.tar.gz
wget output and sha256sum check are OK.
Could you please check if there are any problems on the tarball?

Thanks in advance,
Andrea

**Comment by holtgrewe** [comment]
Dear Andrea,

thanks for the report. I just did the following to reproduce

- download https://file-public.bihealth.org/transient/varfish/varfish-site-data-v0.22.2-20210212.tar.gz
- verify that the sha256sum is `1eb2199d1849d6669c8e52f0cc7e253f29b3fd83f0131780505805f1b1e014ba`
- perform a `tar tf 1eb2199d1849d6669c8e52f0cc7e253f29b3fd83f0131780505805f1b1e014ba`
- and the checksums were correct and the tarball file extracted

In other words: I could no reproduce the problem that you are seeing.

Also, we know of at least one site that has setup VarFish with our instructions and files successfully.

I was running

- CentOS 7.9
- GNU tar .26
- gzip 1.5

Some more questions:

- Could you try again whether the problem still happens to you?
- Do you have sufficient space? Although I don't understand how a non-corrupted download by sha256sum could fail which is also what probably puzzles you.

Could you run ` gzip --test --verbose varfish-site-data-v0.22.2-20210212.tar.gz` to see whether the gzip archive was broken? If the problem persist then please drop me a line on my work email that you can find on my [Github profile](http://github.com/holtgrewe).

Cheers,
Manuel

PS: We would be happy to learn more about your experience once you get VarFish running. This request clearly does not have a ticket system character so feel free to contact me via my work email.

**Comment by holtgrewe** [comment]
drop me a line so we may organize a zoom session for some interactive debugging, is what I meant.

**Comment by aciolfi** [comment]
Hi Manuel,
Thank you for your reply. Unfortunately, I still receive the same error. The sha256sum is correct. When I try to extract the archive using your command, I always get same error, after a while:

```
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

I’ve tested the whole process on CentOS 7.4 (also on MacOS 11.2), using GNU tar 1.26 and gzip 1.5. I have enough space on disk. 
If I try `gzip —test —verbose` command, the system apparently freezes for hours, without any messages...

Cheers,
Andrea

**Comment by holtgrewe** [comment]
Dear Andrea, could you confirm that you run a 64 bit system (could you share `uname -a`?)

**Comment by aciolfi** [comment]
Yes, absolutely.
In any case, the result of the `uname -a` command is the following:
`Linux r033c01s03 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Thanks,
Andrea

**Comment by holtgrewe** [comment]
OK... :shrug: 

I'm rebuilding the data tarball from scratch and will upload it again. Please allow for about one work day.

**Comment by holtgrewe** [comment]
OK, the tarball is currently building. I should be able to upload it tomorrow...

**Comment by aciolfi** [comment]
OK, thanks a lot!

**Comment by holtgrewe** [comment]
OK, the data has been uploaded. Could you give feedback whether your problem persists?

**Comment by aciolfi** [comment]
Yes, absolutely. I’ll let you know as soon as possible.

Thanks
Andrea

Il giorno mer 31 mar 2021 alle 08:03 Manuel Holtgrewe <
***@***.***> ha scritto:

**Comment by aciolfi** [comment]
Hi Manuel,

Bad news: The problem is still there...I will think about it to find another possible workaround...

However, thank you very much for your support.

Cheers,
Andrea

**Comment by aciolfi** [comment]
Hi Manuel, 

Good news: Finally, it worked.
I’ve started again the whole process on another machine: while the old tarball still have the integrity problem, the new one (v0.22.2-20210330) does not show this issue, and so I could extract the whole archive...

Thank you for your support,
Andrea

**Comment by holtgrewe** [comment]
Great. 🎉 

Let us know how it works for you from here and whether you need any more help.
