### ISSUE TITLE
Opening and editing case status of case R13_1 in AG Mundlos/Limb Cohort Genomes/Cases

### ISSUE THREAD

**Issue by sczakihl** [bihealth/varfish-server#331]
**Describe the bug**
Error message and failure upon trying to open case R13_1 in the limb cohort genomes. Also no small variants are called for this case.

**To Reproduce**
1. Go to  Home/Charite/Medical Genetics/AG Mundlos/Limb Cohort Genomes/Cases
2. Click on R13_1
3. Scroll down to  - n.a.
4. See error: see below

**Expected behavior**
Most important: allowing entering and editing this case: to set the status to uncertain, in order to exclude all uncertain cases, in order to be able to perform cohort filtration, which does not work as long as there are cases with no small variants called.
Later: Fix these four cases and why there are no small variants called.

**Screenshots**
<html><body>
<div id="summary">
  <h1>KeyError
       at /variants/f6da38c1-d8d8-4a36-abdb-29b40a7db4ab/case/5a185fd0-a9fb-4b7b-8366-416c381555af/</h1>
  <pre class="exception_value">295</pre>
  

Request Method: | GET
-- | --
https://varfish.bihealth.org/variants/f6da38c1-d8d8-4a36-abdb-29b40a7db4ab/case/5a185fd0-a9fb-4b7b-8366-416c381555af/
3.2.12
KeyError
295
/usr/src/app/variants/views.py, line 893, in get_annotations_by_variant
/usr/local/bin/python
3.8.12
['/usr/src/app',  '/usr/src/app',  '/usr/local/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages',  '/usr/src/app/src/drf-keyed-list',  '/usr/src/app/src/django-sodar-core',  '/usr/src/app/src/django-plugins',  '/usr/src/app/src/django-cryptographic-fields',  '/usr/src/app/varfish']
Wed, 02 Feb 2022 13:24:24 +0000

</div>

<div id="traceback">
  <h2>Traceback <span class="commands"><a href="https://varfish.bihealth.org/variants/f6da38c1-d8d8-4a36-abdb-29b40a7db4ab/case/5a185fd0-a9fb-4b7b-8366-416c381555af/#" onclick="return switchPastebinFriendly(this);">Switch back to interactive view</a></span>
  </h2>
  
  <form action="https://dpaste.com/" name="pasteform" id="pasteform" method="post">

  <div id="pastebinTraceback" class="pastebin" style="display: block;">
    
    
    
    
    </div></form></div>
</body>
</html>

Environment:

Request Method: GET
Request URL: https://varfish.bihealth.org/variants/f6da38c1-d8d8-4a36-abdb-29b40a7db4ab/case/5a185fd0-a9fb-4b7b-8366-416c381555af/

Django Version: 3.2.12
Python Version: 3.8.12
Installed Applications:
['django_su',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.admin',
 'crispy_forms',
 'rules.apps.AutodiscoverRulesConfig',
 'djangoplugins',
 'pagedown',
 'markupfield',
 'rest_framework',
 'knox',
 'aldjemy',
 'adminalerts',
 'userprofile.apps.UserprofileConfig',
 'projectroles.apps.ProjectrolesConfig',
 'timeline.apps.TimelineConfig',
 'siteinfo.apps.SiteinfoConfig',
 'docs',
 'dal',
 'dal_select2',
 'cryptographic_fields',
 'rest_framework_httpsignature',
 'webpack_loader',
 'django_saml2_auth',
 'dj_iconify.apps.DjIconifyConfig',
 'varfish.users.apps.UsersConfig',
 'clinvar.apps.ClinvarConfig',
 'clinvar_export.apps.ClinvarExportConfig',
 'cohorts.apps.CohortsConfig',
 'conservation.apps.ConservationConfig',
 'dbsnp.apps.DbsnpConfig',
 'frequencies.apps.FrequenciesConfig',
 'hgmd.apps.HgmdConfig',
 'geneinfo.apps.GeneinfoConfig',
 'importer.apps.ImporterConfig',
 'genomicfeatures.apps.GenomicFeaturesConfig',
 'pathways.apps.PathwaysConfig',
 'variants.apps.VariantsConfig',
 'bgjobs.apps.BgjobsConfig',
 'var_stats_qc.apps.VarStatsQcConfig',
 'templatetags.apps.TemplatetagsConfig',
 'svdbs.apps.SvDbsConfig',
 'svs.apps.SvsConfig',
 'extra_annos.apps.ExtraAnnosConfig',
 'tokens.apps.TokensConfig',
 'maintenance.apps.MaintenanceConfig',
 'regmaps.apps.RegmapsConfig',
 'beaconsite.apps.BeaconsiteConfig',
 'storages',
 'gunicorn']
Installed Middleware:
['whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/src/app/src/django-sodar-core/projectroles/views.py", line 134, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/src/app/src/django-sodar-core/projectroles/views.py", line 390, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/usr/src/app/variants/views.py", line 936, in get_context_data
    result["commentsflags"] = self.join_small_var_comments_and_flags()
  File "/usr/src/app/variants/views.py", line 1152, in join_small_var_comments_and_flags
    return get_annotations_by_variant(case=case)[case.sodar_uuid]
  File "/usr/src/app/variants/views.py", line 893, in get_annotations_by_variant
    case_uuid = case_id_to_uuid[flags.case_id]

Exception Type: KeyError at /variants/f6da38c1-d8d8-4a36-abdb-29b40a7db4ab/case/5a185fd0-a9fb-4b7b-8366-416c381555af/
Exception Value: 295

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Education
 - Browser: Firefox
 - Version: 96.0.2 (64-Bit)

**Comment by holtgrewe** [comment]
Fixed
