### ISSUE TITLE
ACMG Variant Classification for Class II is inaccurate

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#359]
**Describe the bug**
Classifying a variant using benign criteria (BA/BS/BP) results in an wrong grade if 1 BS and 1 BP is used. According to Richards et al 2015 this should result in a *likely benign* classification, instead a *variant of unknown significance* is shown.

**To Reproduce**
1. Filter variants in a single case or open Variant Annotation tab in a single case. 
2. Click on 'singlevar-acmg-rating' button for a single variant.
3. Check 1 BS and 1 BP box.
4. Check the resulting automatic ACMG classification.

**Expected behavior**
ACMG Class II should be shown in the automatic ACMG classification.

**Screenshots**

![image](https://user-images.githubusercontent.com/3340720/155164889-c87e093d-cc19-44f4-8a89-806f2796977d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by xiamaz** [comment]
The classification is currently set here: https://github.com/bihealth/varfish-server/blob/4e3d07784f41d0c8cc9cc9d57df16c63a84fe830/varfish/static/js/flags_comments.js#L478

Changing this line to use 2 BP or 1 BA & 1 BP should fix the issue.

**Comment by holtgrewe** [comment]
Thanks, good catch. Will fix ASAP.
