### ISSUE TITLE
Scoring Variants with MutationTaster is broken

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#423]
**Describe the bug**
Cannot score variants with MutationTaster

**To Reproduce**
1. Filter a case
2. Use MutationTaster for scoring variants
3. Look into logs

**Expected behavior**
Filtration should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/521780/160797922-4c819a39-161a-4a2b-8f6d-12537a725f17.png)

**Additional context**
N/A

**Comment by domibln** [comment]
We have changed the URLs to allow to switch between MutationTaster versions.

85: https://www.mutationdistiller.org/MTc85/MT_API.cgi / https://www.genecascade.org/MTc85/MT_API.cgi
102: https://www.genecascade.org/MT2021/MT_API102.cgi

It's still a bit intransparent - I'll create a ticket in out gitlab...

**Comment by holtgrewe** [comment]
@domibln thanks for the heads-up!
