### ISSUE TITLE
Allow multiple annotations for single variants (one per user) (WAS: Allow for comments in training filter mode)

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#426]
**Is your feature request related to a problem? Please describe.**

For exome cases often a second look should be performed by another investigator. Currently the second investigator will directly see the assessments of the primary investigator. As a second look should independently assess the given evidence, these prevous comments might bias the 2nd look investigator.
Currently varfish already implements a training mode. While the training mode successfully removes the previous annotations from the filter view, the secondary investigator is unable to add their own comments to variants.

**Describe the solution you'd like**
The training mode should allow for adding comments and independent variant assessments.

**Comment by holtgrewe** [comment]
@xiamaz thanks for the suggestion. This goes into the same direction as #192. We should rephrase your feature request for the feature requested in #192. The training mode just suppresses all annotation. What we need is to maybe hide annotation of other users and then adding and not overwriting the assessment.

**Comment by xiamaz** [comment]
Today in the clinical meeting, we discussed that we want to further improve on the current second look approach, for this we would like to blind the secondary investigator and assess whether their variant assessments actually match.

Since we would like to utilize this as soon as possible in the clinic, I would like to further specify this issue, also in respect to #192.

## Planned workflow

Let there be two or more investigators. All investigators will independently filter and comments variants in a case.

For any given investigator the following steps will be done concurrently:

1. Filter variants, existing ACMG classifications and comments, unless by oneself should not be shown.
2. Comment variants and optionally give an ACMG rating.

After all investigators are finished, differences between investigators should be resolved. Differences should exist, if the given ACMG rating between any investigator differs.

After conflict resolution, the investigators will proceed with finalizing the case and creating a case report.

## Needed features

### Blind variant assessment

An additional filter option should be added for blind variant assessment. This option should remove any comments not done by oneself from the filter view.

### ACMG classification conflict resolution

The variant overview list should highlight conflicting variant assessments. An interface should exist to resolve conflicts and assign a final assessment, including a comment for such a decision.

## Open questions

1. Should any user be able to resolve variant conflicts?
2. Should conflict resolution be possible from the filter view when blind filtering is not used?

@holtgrewe Could you assess, how complex this would be to integrate into the current varfish structure? It would be great if we could further refine this plan and come up with a reasonable user experience.

**Comment by alexejknaus** [comment]
A question could also be wether at all a ACMG classification conflict needs a resolution. Since there are cases, where a pathogenic variant with low penetrance may be pathogenic in the index, but does not affect the mother, e.g.

As ACMG classifications are variant based and not case based, such conflicts may remain, but should be annotated and explained by the analyst in the comments.

**Comment by alexejknaus** [comment]
![Multiuserflagannotation](https://user-images.githubusercontent.com/37909805/162201258-57293c6d-4911-40ab-9b84-c87fb08bb35b.png)
This is how it may look like

**Comment by holtgrewe** [comment]
I really like the idea of not storing the consensus but displaying it only.

**Models**

I would modify the models `SmallVariantFlags` and `AcmgCriteriaRating` to add an `user` field that points to the `User` model. All ratings are always associated with a user. For existing records this field is `NULL`. The "save" button will be labeled with `save and claim this annotation` in this case and the user field is set to the the current user.

**Variant Filtration View**

Consider the following user interface part (Shutter is a good Linux app for annotating screenshots by the way). Users can click on the per-variant variant flags/acmg rating button (1) or select multiple variants there. The comments & flags (2) section displays each user's flags and comments. I don't have a mockup here but separating this as you did in the sketch in the call on April 12 was nice. WE probably also want to display each user's ACMG rating here but that might be pretty UI heavy. When the user uses the "grade multiple variants" then the multi-variant grading popup is shown.

![Screenshot 2022-04-12 at 11-31-49 VarFish Athenea Filter Variants](https://user-images.githubusercontent.com/521780/162931625-22072786-2d90-4e69-8ef6-f2429971d36b.png)

The following is the base "flags and comments view"

![Screenshot 2022-04-12 at 11-32-18 VarFish Athenea Filter Variants](https://user-images.githubusercontent.com/521780/162934377-f6fda916-1eba-4fc0-a8c1-cba6bbbb9a42.png)

and here is the view when modifying multiple variants. There is a notification area that warns in the case that there are conflicting assessments between any selected variants' annotation.

![Screenshot 2022-04-12 at 11-32-35 VarFish Athenea Filter Variants](https://user-images.githubusercontent.com/521780/162934449-076cb3e6-cd0a-43c3-8a5c-9bf5196a1cae.png)

And here is the view for editing the ACMG rating:

![Screenshot 2022-04-12 at 11-33-24 VarFish Athenea Case Details HG00253](https://user-images.githubusercontent.com/521780/162935237-253c3cd5-979d-4e9d-a36c-cbcb099b6583.png)

The variant detail flags and comment view works as in Alexej's example:

![image](https://user-images.githubusercontent.com/521780/162934797-0cf21f5c-db57-492e-abcc-15275a208ba4.png)

We display the different users' assessment and display a :heavy_check_mark: in the case of consensus and :heavy_multiplication_x:  when there is a conflict. In the case of "empty"/"no assessment", any other value overrides the missing data.

So what are the possible actions here?

- User clicks variant flags/comments or ACMG rating button ((1) above) in the variant row to edit a single variant.
  - Effect: popup or modal with the appropriate window from above.
  - Users can set the variant flagging/assessment (see screenshots above) and save it, or add a comment.
  - The corresponding flagging or ACMG rating model is saved for the given user
- User selects multiple variants (left of (1) above) and clicks the flagging/acmg rating button ((1) above)
   - The corresponding popup/modal appears and users can adjust their settings (and their own only)

Right now we update the variant row "in real time" after saving which would be nice behaviour to keep. It is fine to only display the variant assessment/comments in the detail fold-out ((3) above) after the next filtration step.

This does not add any new "clickable areas" so far and only defines how the existing interface is updated to allow for per-user comments.

**Case Overview**

The variants are also displayed in the case overview.

![Screenshot 2022-04-12 at 12-08-44 VarFish Athenea Case Details HG00253](https://user-images.githubusercontent.com/521780/162936962-6052d3da-5c32-4677-b7f0-cc25897d283c.png)

Here, users can:

1. See the ACMG rating
2. See the generic flags
3. See the color-coding flags and comments
4. Update the generic flags and ACMG rating
5. Select multiple variants and
6. Update multiple variants at once

Clicking the "Update Variants" button for generic flags currently triggers display of the update variants generic flags modal, the same is true for the ACMG assessment. This "screen" is used for curating variant assessment after the filtration of variants. We want to also use this screen for multiple analysts to sit together and reach consensus.

We need the following adjustments:

- Display ACMG rating, generic flags, and color-coded flags per user.
- Display where consensus exists and where it does not.
- Edit the generic flag or ACMG rating of all users.

I see two ways forward:

1. Either display the "update" button for each variant and user. This would make semantics a bit difficult with multi-variants.
2. Or change the popups for editing the annotation with a drop-down which displays the list of all users who have created a variant assessment.

I prefer (2). In the single-variant view functionality is obvious. In the case of multi-variant updates, we use the conservative approach of displaying all users that have made an assessment of any of the displayed variants. We update only the variants assessments for users that have previously made an assessment.

**Switch Blinded/Non-Blinded Case**

This is more tricky. We eventually need to support cases going from a "clinic" case to a "research" case where a four-eye principle might not be of importance.

We add a per-query setting in the form on the top that allows users to chose the annotation mode. This also controls how result rows are colored. We add a global per-project setting that determines the default mode for all cases from a project. When not given,t he default will be "blinded: no, research".

Using the setting "blinded: yes" displays only the current user's annotations and row coloring.

Using the setting "blinded: no, clinic displays all user's annotations and row coloring. Conflicting rows will be highlighted in a "special" way that shows lines with conflicting interpretation. For example, yellow-black diagonal stripes could be used. ":construction:".

In the case of "blinded: yes" and "blinded: no, clinic", users only edit their own variant flagging and assessment.

Using the "blinded: no, research" setting displays all user's annotation. In the case of conflicts, the current user's one will be used as the override (if any).

This last part is a bit sketchy and we have to work on a good "story".

**Comment by incardon** [comment]
> I would modify the models SmallVariantFlags and AcmgCriteriaRating to add an user field that points to the User model. All ratings are always associated with a user. For existing records this field is NULL. The "save" button will be labeled with save and claim this annotation in this case and the user field is set to the the current user.

One possibility is to use the timeline to reconstruct the user entry

**Comment by holtgrewe** [comment]
> One possibility is to use the timeline to reconstruct the user entry. But the database migration is more complex

I don't think that this is worth the extra work. Also, I'm not 100% certain the timeline has all relevant information.

**Comment by holtgrewe** [comment]
> 1. Reconstruct information who did flag_set events, and associate event to user.
> 2. Run through DB, create patch to migrate annotations from non-user based to user specific annotations in DB.

I don't think it's worth it or feasible. The timeline integration was added at some point but there is not guarantee (yet) that it is 100% correct.

> 1. Consensus: Computation of the multi user annotations (if no match with users, show MISSMATCH triangle icon), if match then show the consensus.

Agreed

> 2. Row coloring is based on consensus of annotations.
> 2.3. If discrepancy in consensus: show row color light grey and a yellow "!" that on hoover tooltip: "discrepancy in annotations"
> 2.4. If user adds annotation, then display row color according to user based annotation and display "!"

OK, we will have to agree on the use cases in research and how a twice-annotated case is converted into a research case.

>  3.3. The user can see all details of an annotation / ACMG rating from all users, but may only edit his own rating/annotations. Comments are only possible in its own ratings/annotations (--> no comment field when clicking other users annotations).

We need to differentiate between blind clinic and non-blind clinic and research mode.

> in Case View: Variant Annotation
> All Annotations, final ACMG ratings and Flags are displayed in tabular view per variant.
>
> The consensus of annotations and ratings is on top of each variant.
> below are the user based annotations and ACMG ratings.
>
> 2.1. upon clicking on an annotation / acmg rating of another user the balloon with their selections opens.
> 2.2. upon clicking on your own annotation a user can only change it and comment it (a module for annotations opens the background of the screen gets dark. another opened annotation /acmg rating view from another user remains open)

I'm not certain that I get 100% what you mean. Can you make/adjust mockups with clickable areas and what happens if X is clicked, step by step.

**Comment by alexejknaus** [comment]
> I'm not certain that I get 100% what you mean. Can you make/adjust mockups with clickable areas and what happens if X is clicked, step by step.

OK I'll try my best in **Case View** --> **Variant Annotation:** 
![12345](https://user-images.githubusercontent.com/37909805/163155043-f6a69047-766b-4d2d-aeae-5d5920332429.png)
Lets say you have two Annotations with ACMG ratings from two different Users: _Knaus_  (me) and _other user_ (not me) `A.` and `B.`, respectively.

- upon clicking `1` on the ACMG rating for variant `B.` _knaus_ will see the criteria applied, but may not edit them: `2``
- likewise _knaus_ may not update the annotations of _other user_ : `3`

![123456](https://user-images.githubusercontent.com/37909805/163156199-909e332e-968b-4ebd-9a62-00472f7f5564.png)

- upon clicking on `4`update a my AMCG rating in order to reach consensus (not displayed in this mockup) the module for ACMG rating opens (dark semi transparent background, but AMCG rating of previous view `1` is still open and visible, for comparison of what criteria were diffenerent.

**Comment by holtgrewe** [comment]
OK, I believe that I get it now. I don't think that this works well from a UI-wise perspective.

First of all, we should not introduce any new popovers (what you have in your first drawing) but restrict ourselves to modals only. There can always only be one modal but that can contain arbitrary things.

I think we should allow the user to modify other user's assessments (flags/color code/ACMG) in the case view.

I would propose something like this, shown here for ACMG rating only.

The "Variant Annotation" tab in the case overview displays one row per variant. There is a "sub row" for each user that has made an assessment and in the row, the flags and ACMG assessment are displayed.


```
+-------------------+---------------+-------+-------+-------------+--------------+---------+
| chrom-pos-ref-alt | genes/effects | user  | flags | color codes | acmg ratings | buttons |
+-------------------+---------------+-------+-------+-------------+--------------+---------+
...
+-------------------+---------------+-------+-------+-------------+--------------+---------+
| chr1-123-A-C      | ABCD miss.    | knaus | ....  | ....        | 4 X          | edit..  |
|                   |               | holtgr| ....  | ....        | 4 X          | edit..  |
+-------------------+---------------+-------+-------+-------------+--------------+---------+
...
+-------------------+---------------+-------+-------+-------------+--------------+---------+
```

This would indicate that there are discrepancies between the ssessment of knaus and holtgr although both gave 4-LP.

When the user clicks "edit", modal pops up that works as the current one but has a per-user dropdown on the top right as shown below.

![image](https://user-images.githubusercontent.com/521780/163167739-a1a302da-de3f-47c1-b099-1ba45b070fa6.png)


The entry for the user that corresponds to the originally clicked to button is displayed by default but users can switch between the annotations.
Further, there is a diff mode checkbox. When that box is checked then the modal contains two ACMG ratings.

![image](https://user-images.githubusercontent.com/521780/163167709-c2de446f-b7a4-4637-a7fb-5dbff8a2ec21.png)


The user can select a user's ratings for the left and for the right side and the window highlights the conflicts.
The two data analysts can sit together in front of this window and decide on reaching a consensus.
We probably only want one "save" and one "cancel" button a but a "reset to last saved state" button for both windows.

**Comment by incardon** [comment]
**Implementation Proposal**
The Filter Variants change:
    Comments & Flags section split
    
![Selection_001](https://user-images.githubusercontent.com/11769862/164170191-bc1d1292-1db0-4b9b-99e9-922586a36e6d.png)


**Affected Components**
e.g. VarFish server

**Affected Modules/Files**
e.g. variants module or queries.py

**Required Architectural Changes**
e.g. Function F needs to be moved to X.

**Implementation Sketch**
e.g. Change X in F. Then do Y.

**Comment by holtgrewe** [comment]
After several discussions on VarFish developer VCs, this probably needs splitting into several parts.

1. Allow two or more users to create a small variant flag / acmg rating for a variant.
2. Add appropriate UI to reach consensus. More than one mode are necessary here, is a per-project setting with a per-installation default."Trusted" - users sit together on one computer with one account and can adjust assessment of other accounts.
    - "Non-Trusted" - users can only adjust their own assessments.
3. Moving between "clinic blinded", "clinic non-blinded" and "research mode"
    - clinic blinded: one assessment per user and case and variant, can only see own assessment
    - clinic non-blinded: one assessment per user and case and variant, can see all assessments
    - research: shared single assessment, can adjust all

In any case, we need to add a timeline entry for any change done by any user.

**Comment by holtgrewe** [comment]
This issue has become too complex. After discussion in the central VarFish VC and talking to people in Berlin, I broke it out to the following (related) issues:

- #474 
- #475 
- #477

**Comment by holtgrewe** [comment]
We should continue discussion in these tickets, starting out with concepts and requirements before we discuss UI and implementation.
