### ISSUE TITLE
GE PanelApp Gene Symbols not found

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#432]
**Describe the bug**
Utilizing Gene Allowlists loaded from the GE PanelApp dropdown does not work for certain panels, specifically the Intellectual Disability panel.

**To Reproduce**
1. Go to Filter Variants
2. Click on More>Gene Lists and Regions
3. Go to Gene Allowlist Section
4. Click on "Add from GE PanelApp" and select "Intellectual Disability v3.1544" (this should add all genes on that panel, keep confidence at Green)
5. Click on Filter&Display

**Expected behavior**
Varfish should filter and display results.

**Actual behavior**
The following error is shown:

```
Can't find symbol, Entrez ID or ENSEMBL gene ID: C5orf42; ISPD; MUT; TMEM5
```
**Screenshots**
![image](https://user-images.githubusercontent.com/3340720/162159116-8d5b500a-3862-4829-8f00-a0737af8e9ba.png)

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
The given gene IDs are not the official names (any more). VarFish does not use old symbols to prevent name clashes. VarFish expects Entrez gene ids or ENSEMBL gene ids or official HGNC symbols. The PanelApp API returns a number of formats.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Allow VarFish gene queries use HGNC IDs in addition to the other options and use these IDs from the PanelApp API results.

**Affected Components**
VarFish server

**Affected Modules/Files**
- `varfish/static/js/panelapp.js`
- `variants/forms.py`
- `variants/queries.py`
- `variants/templates/variants/filter_form/genelists.html`
- `svs/templates/svs/filter_form/genelists.html`

**Required Architectural Changes**
None

**Resolution Sketch**
- make panelapp JS use the HGNC ID
- allow HGNC IDs in form validation
- allow HGNC IDs when building query
- adjust templates to show that HGNC IDs are fine
