### ISSUE TITLE
Extra annotations for GRCh37 use wrong coordinates

### ISSUE THREAD

**Issue by boschann** [bihealth/varfish-server#450]
**Describe the bug**
The CADD-Score which is displayed at the results level does not match the CADD-Phred Score that is displayed in the Extra Annotations section. 

**To Reproduce**
1. Filter case and annotate with CADD variants
2. Open the fold-out for a variant
3. See that the extra annotations CADD score is different

**Expected behavior**
The scores should be the same.

**Screenshots**
N/A

**Additional context**
- This is using the Berlin internal instance.
- https://github.com/bihealth/varfish-db-downloader/issues/15

**Comment by holtgrewe** [comment]
Please use the [issue template](https://varfish-server.readthedocs.io/en/latest/developer_templates.html) in the future

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
See https://github.com/bihealth/varfish-db-downloader/issues/15.

**Comment by holtgrewe** [comment]
:scream: OK, the "variant prioritization" CADD score is correct, the extra annotations are wrong. Also, all extra annotations are wrong!

**Comment by holtgrewe** [comment]
**Resolution Proposal**
We need to debug and fix the download scripts and regenerate the extra annotation TSV file. We then need to rebuild the data release (create a 20210728b release) and also the prebuilt database files. We need to document this clearly (e.g., in the update instructions) and send out an email to all users that we know of.

**Affected Components**
- VarFish DB Downloader
- VarFish data
    - VarFish data `.tar.gz.` download file
    - VarFish prebuilt databases

**Affected Modules/Files**
VarFish DB Downloader `snakefiles/GRCh3_/extra_annos.smk`

**Required Architectural Changes**
None

**Resolution Steps**
- [ ] fix snakemake files
- [ ] rebuild TSV file
- [ ] create patch `.tar.gz` file
- [ ] create/rebuild 20210728b release
- [ ] create/rebuild GRCh37 prebuilt databases
- [ ] document these issues clearly, e.g., in the changelog
- [ ] inform all users

**Comment by holtgrewe** [comment]
Updated TSV files are now available here:

- https://file-public.cubi.bihealth.org/transient/varfish/athenea/

The fix to the prebuilt database will be forthcoming.

**Comment by holtgrewe** [comment]
Resolved now.
