### ISSUE TITLE
Demo mode does not display welcoming page

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#458]
**Describe the bug**
VarFish demo mode (varfish-demo.bihealth.org) does not display the welcoming page created for the demo mode but the common login mask.

**To Reproduce**
1. Go to https://varfish-demo.bihealth.org
2. See error

**Expected behavior**
Display the welcoming page in demo mode:

> <p>Login as user <u><tt>demouser</tt></u> with password <u><tt>varfishdemo</tt></u>. This site hosts data from the public domain (thousand genomes project) for demonstration purposes. For protection against vandalism, all user-entered data will be cleared nightly (Berlin time).</p><p>If you want to upload your data, then have a look at <a href="https://varfish-kiosk.bihealth.org">varfish-kiosk.bihealth.org</a>. Consult the <a href="https://varfish-server.readthedocs.io">manual</a> on how to create your own VarFish installation.</p>

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
We used the default login template again.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Replace the login page template by something that interprets the `VARFISH_LOGIN_PAGE_TEXT` setting again.

**Affected Components**
VarFish Server

**Affected Modules/Files**
`varfish/templates/users/login.html`

**Required Architectural Changes**
None

**Resolution Sketch**
Port the older code of the `login.html` template that interprets the `VARFISH_LOGIN_PAGE_TEXT` setting.

**Comment by holtgrewe** [comment]
This should also be backported to the `athenea` branch.
