### ISSUE TITLE
Implement easy-to-use "find second hit" functionality

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#47]
**Is your feature request related to a problem? Please describe.**
For recessive diseases, the users need to be able to quickly find all possible variants for a given gene.

**Describe the solution you'd like**
This functionality needs to be easily available without disrupting the overall analysis workflow.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by xiamaz** [comment]
This has been implemented in https://github.com/bihealth/varfish-server/issues/573
