### ISSUE TITLE
ACMG PM2 should be supporting only

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#471]
**Describe the bug**
ACMG PM2 `rare; < 1:20.000 in ExAC` should only be supporting.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
N/A

**Comment by xiamaz** [comment]
This issue should acknowledge that these modifications are often based on later published recommendations by different genetics societes that might not be agreed upon by every lab or genetics society.

It would be great if a solution would allow the definition of specific ACMG rulesets that can be based on arbitrary recommendations. This would allow for keeping old classifications at the correct class, while allowing for future changes and extensions of the ACMG classification system that are bound to come.

**Comment by holtgrewe** [comment]
@xiamaz good point, currently we have ACMG implemented and the downgrading is only true for the SVI representation

- https://www.clinicalgenome.org/site/assets/files/5182/pm2_-_svi_recommendation_-_approved_sept2020.pdf

Also see my comment here that I just rediscovered that goes towards versioning

- https://github.com/bihealth/varfish-server/discussions/202

We should probably have a further discussion how to handle this. Having a generic implementation of variant grading would be nice but I don't see how we can do this in the short term.

For further reference, here is the VarSome implementation of ACMG:

- https://varsome.com/about/resources/acmg-implementation/

**Comment by holtgrewe** [comment]
Closed in favour of #476 and #477.
