### ISSUE TITLE
Filter & Display button broken in Microsoft Edge and Chrome

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#508]
**Describe the bug**
Currently the **Filter & Display** button is clickable only partially clickable when used from the *Prioritization* tab.

**To Reproduce**
1. Filter variants for any case.
2. Select the Prioritization tab
3. Hover over the **Filter & Display** button
4. The button is not clickable in the top half, so a lot of hover artifacts appear.

**Expected behavior**
Buttons should be clickable in the entire button area.

**Desktop (please complete the following information):**
Tested in both Chrome (v101) and Edge (v101). Supposedly Firefox works correctly. (not tested myself)

**Comment by stolpeo** [comment]
## RCA

- **Chrome Version 102.0.5005.61 on Ubuntu 20.04**: not reproducible

**Comment by stolpeo** [comment]
@xiamaz Can you be more specific, i.e. name the case and other settings, VarFish version and activated plugins. I can imagine that a long list of cases during a joint filtration can be the cause, or some other setting.

**Comment by xiamaz** [comment]
No, this issue exists without running any variants beforehand. Just the steps described before are necessary.

I tried reproducing it in some other scenarios:

Chromium Version 102.0.5005.115 on Ubuntu 21.10: not reproducible
Edge Version 102.0.1245.39 on Windows 10 (VDI): reproducible

It is **strictly** necessary to switch to the **Prioritization** tab and the Zoom Factor of the website needs to be set to 100%. I have this issue in any case (but I used LB19_0324 now) and this is on the BIH Varfish.

**Comment by stolpeo** [comment]
@xiamaz thanks for the explanation. I went to the same case in Edge, switching to the Prioritization tab, but still not reproducible for me. That is weird as I can see it happening in your video. Is this dependent on the screen resolution? I resized the VDI window to random sizes but it didn't produce the bug. I'm a bit puzzled.

**Comment by xiamaz** [comment]
Resizing the window to below 1900px width will fix the button issue for me as well

**Comment by stolpeo** [comment]
@xiamaz Ok thanks!

@mikkonie Have you ever encountered this bug? I guess it is better to get rid of the popover, it is clear what the button does and the info seems to do more harm than it helps.

**Comment by mikkonie** [comment]
This is typical malfunctioning behaviour of Bootstrap tooltips. It may be helped by e.g. linking the tooltip to some surrounding element, or tweaking the `display` attribute of the affected element. Most likely some more exotic trickery also exists.

A simple workaround is to simply remove the tooltip and go with the standard HTML `title` attribute itself. It will not look as fancy but at least it works.

At some point I intend to experiment with upgrading SODAR Core to Bootstrap v5 and see if these tooltips work a bit more reliably on the latest version.
