### ISSUE TITLE
CADD setup documenation not complete

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#520]
**Describe the bug**
CADD setup in documentation is not complete.

**To Reproduce**
https://varfish-server.readthedocs.io/en/latest/admin_extras.html#install-scoring-with-cadd

**Expected behavior**
Complete instructions

**Comment by your-highness** [comment]
Thanks@stolpeo!

It's only a minore quirk: It refers to `https://raw.githubusercontent.com/kircherlab/CADD-scripts/7502f47/install.sh` which needs some other files, _e.g._ conda environment yml, for execution. Pull request incoming... 😃 

FYI @selyasar

**Comment by stolpeo** [comment]
Looking good! Could you add an entry to the CHANGELOG file?

**Comment by your-highness** [comment]
> Looking good! Could you add an entry to the CHANGELOG file?

Done. _You were refering to `./HISTORY.rst`?_

**Comment by stolpeo** [comment]
Yes, thanks. It's named differently among our projects.
