### ISSUE TITLE
Improve developer setup documentation

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#533]
**Describe the bug**
While replicating the developer setup in the documentation with the latest Ubuntu LTS (22.04), there were some inconsistencies:
- In vue.js setup: the npm package had to be installed explicitly (`nodejs` was not enough).
- `install_os_dependencies.sh` has to be called

**To Reproduce**
Setup developer setup from scratch.

**Expected behavior**
A complete developer setup without errors.

**Comment by holtgrewe** [comment]
FWIW, here are my notes on an fresh install in Ubuntu 22.04 within WSL2 on Windows 11. I'm installing nodejs from conda by the way.

https://gist.github.com/holtgrewe/f4575f2f871bbe46e00b65fb5227b1d9
