### ISSUE TITLE
dominant / de novo preset broken in certain cases

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#561]
**Describe the bug**
In certain cases the inheritance setting `dominant / de novo` does not set the parents to `0/0` but to `0/1`, e.g. LB22_1299

**To Reproduce**
It is not clear why this happens.
1. Go to case LB22_1299
2. Go to filter page
3. Select `dominant / de novo` inheritance preset or quick preset `de-novo`
4. See all members set to `0/1`.

**Expected behavior**
Parents should be set to `0/0` (index is `0/1` as expected).

**Comment by stolpeo** [comment]
## Root Cause Analysis

The preset relies on `data-` attributes assigned to the HTML elements for each member. These attributes are set correctly.

Checking the JavaScript function, the behavior is as expected as it set unaffected members to `0/0` and affected members to `0/1`. This happens independent of their relation.

```javascript
function enableDomDenovoMode() {
    // All affected will be set to het
    $("[id^=id_][id$=_gt].affected").val("het");
    // All unaffected will be set to ref
    $("[id^=id_][id$=_gt].unaffected").val("ref");
}
```

To my understanding the ticket can be closed as there is nothing to fix.

**Comment by holtgrewe** [comment]
To elaborate, VarFish currently does not have the concept of "de novo" genotype patterns only of "dominant" ones. When the index is affected and the parents are unaffected then this corresponds to the desired de novo. However, here all individuals in the pedigree are flagged as affected so dominant inheritance works as expected.

**Comment by stolpeo** [comment]
I'm closing the ticket, follow-up: #562
