### ISSUE TITLE
Distinct de novo inheritance preset setting

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#562]
**Is your feature request related to a problem? Please describe.**
The inheritance filter preset `dominant / de novo` uses a dominant setting (i.e. setting all affected to het (`0/1`) and all unaffected to ref (`0/0`)). If parents are unaffected this leads to the intended `de novo` settings, but not if any of the parents is affected.

**Describe the solution you'd like**
We need a distinct `denovo` setting, independent of `dominant`. This preset will differ from `dominant` for the genotype in the following:

- The index is set to `variant` rather than `0/1`
- The parents are set to `reference`, regardless of their "affected" status

**Describe alternatives you've considered**
Leave as it is. Which is probably fine as it covers a majority of the use cases.

**Additional context**
- Discussion started in #561.
- This needs to be adjusted both in the `query_presets.py` file for the REST API and the HTML/JS front-end.

**Comment by holtgrewe** [comment]
There is another important use case here.

In the case of de novos on `chrX` of male indices, a value of `0/1` will discard de novo variants on that chromosome. We should also apply `variant` instead of `0/1` for the de novo setting. I'm adjusting the original description to reflect this requirement.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
This is a straightforward adjustment of the current code base (see below).

**Affected Components**
VarFish Server

**Affected Modules/Files**
- `variants`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Possible, but not intended

**Resolution Plan**
Perform the following changes:

- [ ] adjust the front-end JavaScript and HTML with the new setting
- [ ] adjust the related Django server code to the new setting
- [ ] adjust the query generation code with the new setting
- [ ] also integrate these changes in the REST API
