### ISSUE TITLE
Implement filter page in vue.js

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#563]
**Is your feature request related to a problem? Please describe.**
The filter page with rendered Django HTML pages and jquery functions is hitting its limits.

**Describe the solution you'd like**
We require the filter page to be rendered in vue.js.

**Describe alternatives you've considered**
Leave as it is.

**Comment by stolpeo** [comment]
**Implementation Proposal**
Adjust Django views, start vue.js app, transfer JS functions to vue.js app.

**Affected Components**
- VarFish server

**Affected Modules/Files**
- `variants/views.py`
- `varfish/static/js/filter_form.js`
- `varfish/static/js/flags_comments.js`
- `varfish/static/js/state_machine.js`
- `varfish/static/js/variant_carrier.js`
- `varfish/static/js/variant_comments.js`
- `varfish/static/js/variant_validator.js`

**Required Architectural Changes**
- [ ] Introduce vue.js app
- [ ] Split/adapt Django views
- [ ] Transfer JS functions to vue.js app

**Implementation Sketch**

*Django views*

- [ ] Split
    - [ ] `CaseFilterView` into
        - [ ] `PreviousSettingsView`
        - [ ] `SpanrView`
        - [ ] `MustationDistillerView`
        - [ ] `CaddView`
    - [ ] `ProjectCasesFilterView` into
        - [ ] `PreviousSettingsView`
        - [ ] `SpanrView`
        - [ ] `MustationDistillerView`
        - [ ] `CaddView`
- [ ] Return JSON instead of HTML for
    - [ ] `CaseLoadPrefetchedFilterView`
    - [ ] `ProjectCasesLoadPrefetchedFilterView`
    - [ ] `SmallVariantDetails`
    - [ ] `VariantCarriersView`
    - [ ] `VariantValidatorApiView`
- [ ] Obsolete
    - [ ] `SmallVariantFlagsApiView` (replace with `MultiSmallVariantFlagsAndCommentApiView`)
- [ ] Adjust JSON return for
    - [ ] `CasePrefetchFilterView`
    - [ ] `FilterJobGetStatus`
    - [ ] `FilterJobGetPrevious`
    - [ ] `ProjectCasesPrefetchFilterView`
    - [ ] `ProjectCasesFilterJobGetStatus`
    - [ ] `ProjectCasesFilterJobGetPrevious`
    - [ ] `SmallVariantCommentSubmitApiView`
    - [ ] `SmallVariantCommentDeleteApiView`
    - [ ] `MultiSmallVariantFlagsAndCommentApiView`
    - [ ] `AcmgCriteriaRatingApiView`
    - [ ] `HpoTermsApiView`

*vue.js app*

- [ ] Start app; add pinia; get familiar
- [ ] replace functions in `state_machine.js` with https://xstate.js.org lib
    - [ ] Submitting form
    - [ ] Getting current/previous job ID
    - [ ] Getting job state
    - [ ] Loading results
    - [ ] Cancel current filter query
- [ ] `filter_form.js`
    - [ ] `loadVariantDetails()`
    - [ ] `initHpoTypeahead()`
- [ ] `variant_validator.js`
    - [ ] `queryVariantValidatorApi()`
- [ ] `variant_carrier.js`
    - [ ] `showVariantCarrierModal()`
- [ ] `variant_comments.js`
    - [ ] `commentEditSubmit()`
    - [ ] `commentDeleteSubmit()`
    - [ ] `commentSubmit()`
- [ ] `flags_comments.js`
    - [ ] `clickVariantBookmark()`
    - [ ] `clickMultiVariantBookmark()`
    - [ ] `clickVariantAcmgRatingModal()`
    - [ ] `clickVariantAcmgRating()`

**Comment by holtgrewe** [comment]
@stolpeo I believe this is complete?
