### ISSUE TITLE
Clinvar-based filtration leads to duplicate lines

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#565]
**Describe the bug**
When using the "Clinvar pathogenic" preset duplicate lines are possible.

**To Reproduce**
1. Filter the NA12878 trio with "Clinvar pathogenic" filter.
2. See the result: 
![image](https://user-images.githubusercontent.com/521780/176630150-3f838903-38db-4a59-9590-2fd79e6c60c6.png)

**Expected behavior**
Only one line per variant should be shown.

**Screenshots**
See above.

**Additional context**
- Further follow-up: #627

**Comment by your-highness** [comment]
Dear @holtgrewe ,

I think our problem is linked to this issue but not dependent on the "Clinvar pathogenic" preset:

In our Athenea 1.2.1 installation when analysing NA-12878 for the [reported CYP2C19:c.681G>A variant](https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=NA12878#PhenotypicData) with all filters relaxed and "Gene Allowlist" set to "CYP2C19" duplicated lines are observed, _e.g._ for `chr10:96,535,124.A>G` 57 entries where displayed. I commented on one of the entries and all duplicates where shown as "commented" which indicates that the same entry is shown multiple times.

We checked if the imported TSV has multiple variant entries but it was not the case. 

**Config:**
![grafik](https://user-images.githubusercontent.com/1949888/181276468-89d4b911-46e5-41a7-986f-7ce6e3a0fdce.png)

**Results (Snippet):**
![grafik](https://user-images.githubusercontent.com/1949888/181278879-4dd6a33e-cd51-4a77-866d-e9748442ee9d.png)


Best,

**Comment by holtgrewe** [comment]
@your-highness We always join with clinvar. This also occurs outside of the clinvar filter but there the problem is obvious whereas the variants are not so obviously spotted outside.

**Comment by holtgrewe** [comment]
**Further Root Cause Analysis**
Originally, we had only one clinvar record in our internal tables. This changed in the last data release. We did not properly catch this change in VarFish Server.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Adjust `ExtendQueryPartsClinvarJoin` to use a lateral join and merge all records.

**Affected Components**
VarFish Server

**Affected Modules/Files**
`variants.queries`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Yes

**Resolution Sketch**
See above.

**Comment by holtgrewe** [comment]
- main PR is #630 
- backport is #631
