### ISSUE TITLE
Visualize Design Regions with Low Coverage

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-server#575]
**Is your feature request related to a problem? Please describe.**
In NGS diagnostics it is essential to check for design regions lacking coverage which can be caused by faulty probes, bad enrichment or homozygous deletions but also homologies and low complexity regions. 
This issue addresses how a visualization of design regions lacking coverage can be displayed to the user and how this enables a quality control for technical validation of a sample. 
See also Discussion #529 which deals with the main requirements for diagnostics in a regulated setting on defined subpanels in a whole exome sequencing experiment.

**Describe the solution you'd like**
VarFish does not offer the direct processing of read alignment data and, thus, this information has to be supplied in the upload, _e.g._ via a BED, TSV or JSON file.
As a 1st prototype implementation the <20x coverage (a broadly used threshold in germline diagnostics) can be displayed as an table with rows representing genes in a subpanel and columns representing detected coordinates ofinsufficient coverage, _e.g._:
| Gene | % at 20x | Exons affected | 
| ------------- | ------------- | ------------- |
| ABC1  | 95%  | E1_2bp_chr1:10-12 |
| ABC2  | 100%  | NONE |
| ABC3  | 50%  | E2_10bp_chr1:200-210 |

**Describe alternatives you've considered**

- External enlistment of regions with low coverage as TSV or BED. 
- Displaying Low Coverage Regions via BED in IGV

**Additional context**
This quality assessment is directly related to the definition of subpanels within VarFish (#528 ).
This topic was discussed together with Dieter Beule and @holtgrewe on July 5th 2022 together with @your-highness and @selyasar from Labor Berlin.

**Comment by your-highness** [comment]
There is some documentation needed for the ingestion of quality control metrics (#530)

**Comment by holtgrewe** [comment]
I agree, [here is the code in snappy-pipeline](https://github.com/bihealth/snappy-pipeline/blob/master/snappy_wrappers/wrappers/varfish_annotator/bam_qc/wrapper.py#L43) that we use.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
In the core, operators want to annotate "intepretable" genes with coverage information. We can thus assume that it is sufficient to allow annotating genes that have both an Entrez/NCBI and ENSEMBL gene identifier to be annotated for each case. A future-proof annnotation would allow to store models such as the following.


```
class CaseGeneAnnotationEntry(models.Model):
    sodar_uuid = models.UUIDField(default=uuid_object.uuid4, unique=True)
    case = models.ForeignKey(Case)
    gene_symbol = models.CharField(max_length=32, null=False, blank=False)
    entrez_id = models.CharField(max_length=32, null=False, blank=False)
    ensembl_gene_id = models.CharField(max_length=32, null=False, blank=False)
    annotation = models.JSONField(default=dict)
```

We will allow and interpret the following `annotation` keys:

- `percentage_at_20x`, a number between 0 and 100
- `level`, of `['info', 'warning', 'error']`
- `message`, a string to display

We will then display a table on the case page as follows, and color warning rows in yellow and error rows in red.

| gene | % at 20x | message |
|------|----------|---------|
| TTN  |      95% | something |

We will need to add support for this in VarFish Server:

- Add a corresponding model
- Add support for importing it in the `importer` module, in particular a new REST API endpoint
- Display the information on the case overview page

We will further need to add support for uploading a corresponding file with `varfish-cli`.

**Affected Components**
- VarFish Server
- VarFish CLI

**Affected Modules/Files**
- `variants`
- `importer`

**Required Architectural Changes**
None

**Required Database Changes**
- New model `CaseGeneAnnotationEntry`

**Backport Possible?**
Yes

**Resolution Plan**
- [ ] add model, factories, tests
- [ ] add support for importing to importer module with tests
- [ ] add displaying the information to the case overview page
- see XXX for the corresponding varfish-cli ticket
