### ISSUE TITLE
SNV / SV Filter bug

### ISSUE THREAD

**Issue by boschann** [bihealth/varfish-server#587]
1) Detailed information for SNVs are not displayed
2) SVs filtering is not working

1) 
1. Go to 'Filter Variants for Case'
2. Click on 'Filter&Display'
3. Scroll down to 'Results'
4. Click on little arrow for each variant
5. See error "Error during AJAX call:"

**Expected behavior**
1) I would like to see the detailed description of the variant

2)
1. Go to 'Filter SVs'
2. Click on 'Filter&Display'
3. See error: nothing happens

**Expected behavior**
2) I would like to see the filtered SVs

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. Mozilla Firefox]
 -

**Comment by stolpeo** [comment]
@boschann should be working again. Thanks for the report!
