### ISSUE TITLE
Set own default parameters for "Filter Variants" and "Filter SVs"

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-server#593]
**Is your feature request related to a problem? Please describe.**
Our requirements for variant filter parameters differ from the shipped default parameters. _Is there any way to set own default parameters via a config file?_

**Describe the solution you'd like**
A config file that takes a default configuration for filtering parameters.

**Describe alternatives you've considered**
Adapt filters every time "Filter Variants" or "Filter SVs" is opened.

**Additional context**
none

**Comment by your-highness** [comment]
Any comment on this? I see that CUBI instance has filters set per default which are not the shipped filters.

**Comment by xiamaz** [comment]
Which filters did you notice are different between LB and the CUBI instance?

**Comment by your-highness** [comment]
Ok. Now I see it is restoring the lastly used query settings if _"Filter Variants"_ is opened again.
![image](https://user-images.githubusercontent.com/1949888/182606952-3f875f30-8d12-41ea-b1a6-f3b7a7ad8c11.png)

When opening a previously untouched case it seems _"default"_ preset is loaded which is fine. I don't know if it is really _"default"_ because the preset name is not indicated. This explains why filters looked different. Sorry for my mistake.

Regarding the initial questiuon I would like to know how 
1. **the preset _"default"_ can be configured**
2. **new presets can be added**

Thanks in advance!

**Comment by holtgrewe** [comment]
This is not possible from the UI in the current version. See #776 for an upcoming feature. We will not port this back to anthenea, though.

As a workaround for anthenea, you can create a copy of `variants/query_presets.py`, adjust it, and bind mount it into your Docker container.

**Comment by your-highness** [comment]
Thanks @holtgrewe ! We will look into adapting `variants/query_presets.py` to our needs.

One more question:
When opening a previously untouched case it seems _"default"_ preset is loaded which is fine (however it's not indicated). _Is 'default' or 'any' loaded in that case?_ 
_Are presets saved when revisiting a case?_
