### ISSUE TITLE
Exac and thousand genomes settings not shown in frequency tab for GRCh37

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#597]
**Describe the bug**
Frequency tab does not show exac and 1000 genomes settings. However, they are only hidden and set by frequency presets and thus used in the query parameters.

**To Reproduce**
1. Go to filterpage, frequency tab
2. See that they are missing
3. Submit query
4. Get variants filtered out that you might not expect to be filtered out

**Expected behavior**
Show Exac and 1000 genomes settings for GRCh37

**Comment by stolpeo** [comment]
## RCA

The release for support of GRCh38 introduced a switch that hides Exac and 1000 genomes for GRCh38. However the settings were also disabled for GRCh37. Reason is that the genomebuild was set as a parameter to the form, but the form parameter is not accessible in the template.

**Comment by your-highness** [comment]
Sorry for reopening:

_Will this be backported to Athenea?_

**Comment by stolpeo** [comment]
It is in already in the code base (just merged). I will build the Docker image today.
