### ISSUE TITLE
SV Filter Genotype Dropdown broken

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#600]
**Describe the bug**
When filtering SVs for a case, the genotype dropdown is broken in Win10 Chrome on 1920x1200 display in maximized window.

![image](https://user-images.githubusercontent.com/3340720/182548784-eebfa8f2-ca1f-42af-a642-e991b0e2dcc6.png)

It's not possible to scroll down. To see the entries further down, instead the Genotype Individual box is scrolled.

**Comment by holtgrewe** [comment]
should be solved
