### ISSUE TITLE
Possibly in-house DB filter not working correctly

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#605]
**Describe the bug**
The in-house filter behaves weirdly in one site instance. It is not reproducible. The in-house db reports the following count data:

```
count_hom_ref | count_het | count_hom_alt | count_hemi_ref | count_hemi_alt
            0 |         3 |             21|              0 |              0
```

However, the cutoff settings show the variant already at 21. It should be 24 (3+21), though.

https://github.com/bihealth/varfish-server/blob/main/variants/queries.py#L877
https://github.com/bihealth/varfish-server/blob/main/variants/queries.py#L941

**To Reproduce**
Not reproducible

**Expected behavior**
In the above case, cutoff working at 24.

**Comment by holtgrewe** [comment]
The reporting site actually reported that this was caused from multiple imports of the same data and incomplete understanding of what was happening internally in VarFish.
