### ISSUE TITLE
SV filter _"Frequencies in Analysis Collective"_ not working - Possibly due to problems with Collective Count DB

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-server#606]
**Describe the bug**
Using VarFish Docker Athenea v1.2.1 in a project with 5 single cases the Filter _"Frequencies in Analysis Collective"_ (Default settings) does not work correctly:
![image](https://user-images.githubusercontent.com/1949888/182604243-799c5317-563f-4b6f-80e9-23760b7e32d2.png)
This means that per default always no SVs are shown (see also #593). 

When removing filter-option _"Minimal affected carriers in pedigree"_, results show up:
![image](https://user-images.githubusercontent.com/1949888/182604636-01c8f644-86c9-4f46-9512-673934263727.png)
However, _"Collective Count"_ shows `0/0/0` which is not correct and might cause the problem in the first place (see screenshot). 

**To Reproduce**
1. Go to 'Filter SVs'
2. Click on 'Filter & Display'
3. Scroll down to 'Results'
4. All SVs are marked "0/0/0" in Collective Count

Also in Ballonaster (CUBI instance) the same problem occurs for the same project collective.

**Expected behavior**
SVs Frequencies should be shown correctly and considered for filtering.

**Additional context**
A possible workaround is manually removing filter-option _"Minimal affected carriers in pedigree"_ by sacrificing specificity but better would be altering the default parameters in our installation (see #593)

**Shoutout:**
@selyasar @xiamaz

**Comment by holtgrewe** [comment]
SV filtration in anthenea (1.x) is experimental. Actually, the collective counts have to be annotated in the VCF file with

- `BACKGROUND_CARRIERS`
- `AFFECTED_CARRIERS`
- `UNAFFECTED_CARRIERS`

cf.

- https://github.com/bihealth/varfish-annotator/blob/main/varfish-annotator-cli/src/main/java/com/github/bihealth/varfish_annotator/annotate_svs/AnnotateSvsVcf.java#L709

Work to remove this restriction and rather annotate within VarFish itself is on the way for bollonaster/2.x in #32. No backport of this to anthenea/1.x is planned possible as this requires major changes to the database.
