### ISSUE TITLE
Pink colored WIP result rows.

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#673]
**Describe the bug**
Colored rows are pink when work in progress (instead of gray).

**To Reproduce**
1. Go to filter results
2. Flag rows, but not in summary.
3. See pink colored result row

**Expected behavior**
Gray colored row.

**Comment by holtgrewe** [comment]
@stolpeo can this be closed?

**Comment by stolpeo** [comment]
## RCA

The dictionary holding the colors for coloring the rows had accidentally the `wip` entry with color gray removed. This lead to the fact that it fell back to the invalid color (pink) when an entry was considered work in progress. Also two unnecessary entries were added.
