### ISSUE TITLE
Clinvar link redirects to coordinate and not VCV entry

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#693]
**Describe the bug**
The clinvar icon link does not link to the VCV entry but to the coordinates.

**To Reproduce**
1. Filter case
2. Click clinvar icon in result table
3. See that you are redirected into ClinVar by coordinate and not to the VCV record

**Expected behavior**
We should link to the VCV record.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
The link in the template has been changed in the assumption that there may be more than one ClinVar VCV record per variant (#640). This is not the case. We can and should link directly to the VCV record again.

**Comment by stolpeo** [comment]
Question: Before there was only the first clinvar entry returned that matched the coordinates. Now all matching entries are returned. Either, we return VCV entry for all of them or we switch back to the first matching clinvar entry. Which one is to prefer?

**Comment by stolpeo** [comment]
**Resolution Proposal**
Replace coordinates in link-out with vcv entry.

**Affected Components**
- VarFish server

**Affected Modules/Files**
- `row.html` (of results table)
- `clinvar.html` (of variant details)
- `SmallVariantFilterResultsTableVariantIcons` (of vue.js implementation)
- `SmallVariantDetailsClinvar` (of vue.js implementation)

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Yes

**Resolution Sketch**

Replace

```
https://www.ncbi.nlm.nih.gov/clinvar/?term={{ entry.release }}%3A{{ entry.chromosome }}%3A{{ entry.start }}-{{ entry.end }}
```

with

```
https://www.ncbi.nlm.nih.gov/clinvar/?term={{ entry.vcv }}
```

(or similar)
