### ISSUE TITLE
Remove dependency on bootstrap-vue

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#716]
**Is your feature request related to a problem? Please describe.**
The `clinvar_export/vueapp` uses `bootstrap-vue`. This package is not available for Vue.js v3.

**Describe the solution you'd like**
We need to remove the dependency on it before migration to Vue.js v3 is possible.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Replace the `bootstrap-vue` components with plain HTML and Vue.js.

**Affected Components**
VarFish server

**Affected Modules/Files**
`clinvar_export/vueapp`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Yes

**Resolution Sketch**
See above.

**Comment by xiamaz** [comment]
Do we have a CSS framework, such as tailwind, bulma etc. or is the plan to write entirely custom css?

**Comment by holtgrewe** [comment]
@xiamaz We have bootstrap v4 and will stick to it. I'm referring to remove the `bootstrap-vue` component and replace it by plain HTML + Bootstrap rather than relying on the Vue.js v2 components from `bootstrap-vue` as there is no equivalent to `bootstrap-vue` for Vue.js v3.
