### ISSUE TITLE
Fix variant icons opcacity/style when inactive

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#745]
**Describe the bug**
The icons are always dark gray and solid, independent of whether an information triggers this behavior or not.

**To Reproduce**
1. Go to filter page
2. Filter
3. See results list with active icons

**Expected behavior**
Icons should be light gray and in case of comments & flags icons should be regular not solid.

**Screenshots**
![image](https://user-images.githubusercontent.com/1266531/196943712-81454a8f-e2b6-4594-b1c1-dde317c55c70.png)

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
`<style scoped>` is used which makes `.icon-inactive` unavailable when used in ag-grid.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Remove `scoped`.

**Affected Components**
VarFish server

**Affected Modules/Files**
`variants/vueapp/src/components/FilterResultsTableVariantIcons.vue`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
No

**Resolution Sketch**
Change `<style scoped>` to `<style>`
