### ISSUE TITLE
Filter Variants for Case: Include ACMG v3 + v3.1 in Gene Allowlist Presets

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-server#829]
**Is your feature request related to a problem? Please describe.**
Currently, only presets for ACMG v1 and v2 are included per default in "Gene Allowlist" for Filter Query. 
![image](https://user-images.githubusercontent.com/1949888/214601932-ce15dec9-304d-42b6-b6df-8d0fcb4d987c.png)

**Describe the solution you'd like**
Since ACMG v3 and v3.1 (July 2022; https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/) were released already, it would be great to include those

**Describe alternatives you've considered**
Generating a Gene Panel with ACMG_v3 genes. However, this mixes up analytical subpanels with incidental finding workflows.

**Additional context**
- Previous communication with @stolpeo on this topic.
- Please also backport to athenea if possible.

**Comment by stolpeo** [comment]
@your-highness I've extracted the gene names from the table (90 records) and removed duplicates, leaving 78 gene names in total. Could you confirm that this the correct list?

ACTA2
ACTC1
ACVRL1
APC
APOB
ATP7B
BAG3
BMPR1A
BRCA1
BRCA2
BTD
CACNA1S
CASQ2
COL3A1
DES
DSC2
DSG2
DSP
ENG
FBN1
FLNC
GAA
GLA
HFE
HNF1A
KCNH2
KCNQ1
LDLR
LMNA
MAX
MEN1
MLH1
MSH2
MSH6
MUTYH
MYBPC3
MYH11
MYH7
MYL2
MYL3
NF2
OTC
PALB2
PCSK9
PKP2
PMS2
PRKAG2
PTEN
RB1
RBM20
RET
RPE65
RYR1
RYR2
SCN5A
SDHAF2
SDHB
SDHC
SDHD
SMAD3
SMAD4
STK11
TGFBR1
TGFBR2
TMEM127
TMEM43
TNNC1
TNNI3
TNNT2
TP53
TPM1
TRDN
TSC1
TSC2
TTN
TTR
VHL
WT1

**Comment by stolpeo** [comment]
I've also extracted the gene names manually from the paper for ACMG v3.0 and sort-unique'd them:

ACTA2
ACTC1
ACVRL1
APC
APOB
ATP7B
BMPR1A
BRCA1
BRCA2
BTD
CACNA1S
CASQ2
COL3A1
DSC2
DSG2
DSP
ENG
FBN1
FLNC
GAA
GLA
HFE
HNF1A
KCNH2
KCNQ1
LDLR
LMNA
MAX
MEN1
MLH1
MSH2
MSH6
MUTYH
MYBPC3
MYH11
MYH7
MYL2
MYL3
NF2
OTC
PALB2
PCSK9
PKP2
PMS2
PRKAG2
PTEN
RB1
RET
RPE65
RYR1
RYR2
SCN5A
SDHAF2
SDHB
SDHC
SDHD
SMAD3
SMAD4
STK11
TGFBR1
TGFBR2
TMEM127
TMEM43
TNNI3
TNNT2
TP53
TPM1
TRDN
TSC1
TSC2
TTN
VHL
WT1
TMEM127
TMEM43
TNNI3
TNNT2
TP53
TPM1
TRDN
TSC1
TSC2
TTN
VHL
WT1

**Comment by stolpeo** [comment]
**Diff ACMG v2.0 to v3.0**

```
+ACVRL1
+BTD
+CASQ2
+ENG
+FLNC
+GAA
+HFE
+HNF1A
+MAX
+PALB2
+RPE65
+TMEM127
+TRDN
+TTN
```

**Diff ACMG v3.0 to v3.1**

```
+BAG3
+DES
+RBM20
+TNNC1
+TTR
```

**Comment by your-highness** [comment]
Checked! That's correct!

Best to indicate this as ACMGv3**.1** because it differs from ACMGv3 by genes BAG3, DES, RBM20, TNNC1, and TTR. _Is it possible to make ACMGv3.0 and ACMGv3.1 available?_

Also: I am open for pull request reviews 😸

**Comment by stolpeo** [comment]
You are correct, I added another list and assigned you as a reviewer.
