### ISSUE TITLE
[vuejs] small variant filter flags do not immediately update row color after change

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#930]
**Describe the bug**

When flagging a variant in the small variant filter, the color of the row should change according to the status of the flag (green, red, grey, yellow). Currently after setting the flag in the modal the color of the row only changes after a full reload of the query.

**Expected behavior**
After setting the flag the row color should be updated immediately.

**Comment by stolpeo** [comment]
We plan to switch to another table plugin after the clean-up. However, this is definitely a feature we need to implement, but the current table plugin caused problem doing so. We have to postpone the fix, unfortunately.

**Comment by holtgrewe** [comment]
solved by #961 #965
