### ISSUE TITLE
[vuejs] Small variants extra annotations are missing

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#931]
**Describe the bug**
Extra Annotations for small variants (CADD-PHRED, SpliceAI) still seem to be missing in the model popover and the column selection.

**Comment by stolpeo** [comment]
We plan to switch to another table plugin after the clean-up. However, this is definitely a feature we need to implement, but the current table plugin caused problem doing so. We have to postpone the fix, unfortunately.
