### ISSUE TITLE
[vuejs] Filter&Display Query Button does not allow for starting a new query when the previous one is still running

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#939]
In the old interface a user could start a new query when the old query has not finished processing yet directly. Currently this is not possible

**Solution**

Enable the button for submits even when a filter query is still pending.

**Comment by xiamaz** [comment]
Thanks, can confirm this works. Currently the UI still misses the previously shown cancel label when a query has already been submitted. Could this be changed? This can be helpful to reduce confusion on the side of our users.

**Comment by stolpeo** [comment]
Sure, I can do that.
