### ISSUE TITLE
[vuejs] Expand table of identified variants without need to hide filter form

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#953]
**Describe the bug**
In the old variant filter interface, the resulting variant table can be scrolled and is not restricted to the visible area below the filter form. This is a UX regression, as now the filter form needs to be manually hidden to expand the list of variants.

**Comment by stolpeo** [comment]
Thanks, we are aware of that. We will move to a different table plugin after the switch and with the issue will be addressed. Thus we leave it as is for now, but I will also leave the ticket open for the next increment.

**Comment by holtgrewe** [comment]
Solved by #961 #965
