### ISSUE TITLE
Switch to use Pipenv for package management

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#967]
**Is your feature request related to a problem? Please describe.**
Using plain pip and `requirements/*.txt` files works but the environments are not 100% reproducible.

**Describe the solution you'd like**
Switch to using pipenv. Also, update the developer documentation and deployment.

- [ ] add Pipfile and Pipfile.lock and make it work
- [ ] adjust developer documentation
- [ ] adjust Dockerfile

**Describe alternatives you've considered**
Pipenv is another option but does not allow for installing packages and needs a `pipenv sync` to update the `setup.py` file.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Fix needed in an Ubuntu 22 because systempackage versions are broken.

```
sudo mv /usr/lib/python3/dist-packages/distro_info-1.1build1.egg-info /usr/lib/python3/dist-packages/distro_info-1.1+build1.egg-info
sudo sed -i -e 's|1.1build1|1.1+build1|g' /usr/lib/python3/dist-packages/distro_info-1.1+build1.egg-info/PKG-INFO
sudo mv /usr/lib/python3/dist-packages/python_debian-0.1.43ubuntu1.egg-info /usr/lib/python3/dist-packages/python_debian-0.1.43+ubuntu1.egg-info
sudo sed -i -e 's|0.1.43ubuntu1|0.1.43+ubuntu1|g' /usr/lib/python3/dist-packages/python_debian-0.1.43+ubuntu1.egg-info
```

**Comment by xiamaz** [comment]
Poetry does not support editable installs: https://github.com/python-poetry/poetry/issues/34

Why not pipenv?

**Comment by holtgrewe** [comment]
@xiamaz you can just to "pip install -e ." with a recent pip.

With pipenv, you have to sync your setup.py manually for installation.

**Comment by holtgrewe** [comment]
@xiamaz But I have to admit that I cannot get poetry to install pycparser to the user directory. 🤷
